### ISSUE TITLE
problems with the static log_analytics_destination_type property

### ISSUE THREAD

**Issue by stiross79** [equinor/terraform-azurerm-key-vault#42]
#32 

Terraform keeps reporting that it needs to update the `log_analytics_destination_type`  property on some of our existing key vaults. Even thought it applied the changes successfully, they will still show up as "updated in-place " when you run the plan again. I can verify that the value is null in the azure portal, so no changes where applied. I even deleted the old diagnostic setting and let terraform create a new one with the same result.

![image](https://user-images.githubusercontent.com/94676511/216637988-ceca048b-9835-464a-95ef-b4b82c58f360.png)

![image](https://user-images.githubusercontent.com/94676511/216639289-4349d2f9-83a8-43a9-81b8-13c1122eb0a3.png)

![image](https://user-images.githubusercontent.com/94676511/216638056-49c8a9b7-22bb-47de-bf0a-93b56b56867d.png)

**Comment by hknutsen** [comment]
@stiross79 With what version(s) of this module are you experiencing this issue? And are there any versions where the issue does not occur?

**Comment by stiross79** [comment]
I was using v7.1.1, but have now reverted to 7.1.0 as this property where introduced in 7.1.1

**Comment by hknutsen** [comment]
Will investigate.

**Comment by hknutsen** [comment]
Looks like a workaround will be to set the value to `null`. Strangely, ARM reference for diagnostic setting does not show "AzureDiagnostic" as a possible value 🤔 

[Ref.](https://learn.microsoft.com/en-us/azure/templates/microsoft.insights/diagnosticsettings?pivots=deployment-language-terraform#diagnosticsettings-5)

**Comment by stiross79** [comment]
Very strange indeed

**Comment by hknutsen** [comment]
@stiross79 I've opened a PR #43 that should fix this behavior.

**Comment by hknutsen** [comment]
@stiross79 https://github.com/equinor/terraform-azurerm-key-vault/releases/tag/v8.1.1
